CREATE TABLE IF NOT EXISTS anime (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    dub_vote INT,
    sub_vote INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE anime ADD COLUMN IF NOT EXISTS mal_id INT;
